sudo: required
language: android
dist: trusty
jdk: oraclejdk8
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
env:
  global:
  - ANDROID_API_LEVEL=29
  - ANDROID_BUILD_TOOLS_VERSION=29.0.0
  - secure: wjVFwWcWaFYFXHiepcyzm438QdCVJGoHpx0BXRGazVbPtst67SUE2ANjCe2nwtNp51I5uergrukKZe7BI/zmaEIPTHxUUfoYWrpwXXl9OYlTJgDDb2BZpzW0mXASxQ8g+st7pTWZAwIL5MVIhoULDvZDVbT872N4FBx8rjoDWMv/JkZh/LXdIf57cqrEWx3NxfJwT3t77sUlinJaqtxKftGWYbvGu5FfCJQwq+xJ56kVFA1c0cFtHFYTjHdplrzo8ohYAwEPo7UBzWVHtyk9SL70yyFnr9A5Nt8IhCUsgI8K196ZSj4oWQ1E1zTlM/BBkJ7OzkQ9CdPcu0ntbiwGDnLD/db4qntq08PCiI7krLCwPZxstzkSX+WlttESwnSyTYztwl+RRuCY7aEGw/s4vUz09qa0e2J9ZzPlNGGRrse6rgBAKd5n2fqzZEPifd2b7VXVjqg16LysXo/JJ9sxxXYchvWq11mNTfjdQW6KcSGy6Bijt6OF31kvD+0TtH4a5j1KWRxYEzchuNDh9KVK19R6MPnZSHpvWlZlAC8KK03uoPLak4c4vPuRsSXMzFbtvrz+lIs4Lv/jGoTSFmzuuI1j7yGfa5c82RIsYEikvup09bx+PTPsx2xDzVLsEN5+Zi+5FRzxKZwjRlKgp8skeJpVyMCAMLtMvPZ8GWQKHSU=
  - secure: RBWke1okWuF9Zj7RohtWtdWsBD25ANClLMMC4IVzx0BLqFr10J3t1/r52NX89bGDxfc1coS3k0YrXg4s3KOYawwlO+QEB/L6LGB6UyILJHaCNA+JgOI6oW0PMAwkebTvNq+nTyjAbmtxazz3E/gvjEzHwGY4qx70nMv+Y8hmU5REw2MdrF7P03nyU2okAyEQzI1HlBqvG67C2Iqrp1nljnDwd3i6kgQbvUitSssYsJBAu6cTG8q1SMZgNqzgJerifqF+E8XrKGe8SkjiFmpAxBAMlgLFWuaCej5+9tbmKkZwIzmiUXsRExos8lKWvMHaFD8zJDhV3ZxWFXVwfSKlH3Pmc3jJq7N/QTK42pDh/N4SY29eCcPYnP3426HF6JP62yfSm4kKax4ZbvIh/XwgbSLxDT7KkGk1vRI0geJu3NLd2CaxfyZ+oTQonSrffVYASyDVPJv/XdGxDfWXCTHUlrYO4OK0KsQfr9r4pvQTI3d9//Ewkbk9t989kYN30tAV0Qqw5RLjsqTtJU6zlKPCqIvRLWtd1SJozZD85SVDZlDNrZF/dqb/jfL3ng5cecwZhDaTdzO8UaRsew4OxRzGqGlF+wNrhpUXctztcQuY9+lz1H/zPq19gocXTH2vL2mWcy04njDvHthEyyvpytfaqNjKmukWa2GjnHrucuVJ58A=
  - secure: TsPFusBW62Zi08Qo5WDreJTgrQ1C3fjP+5rUGmby3jlM0L+tX+HxANi6L/vw9AMRYo75N0IZriyoGk0k+y6iRY/nQ4A1lJ7GppM5jsQP8JiDdaaCWcYAy9/jZVrgmNg2V9tan+cQdVh2Z1SW1LTcjLzZP9587qmyJNO97/aSsXN3JhVFMDO9Sfv8zVSeavtZDMa1md8QYcgO/qQqE8YiAb1PXqDcKOqXvPwFTcgdzb4ASS5no3cT8BGW9lzhfW2c0PieZhK76fegENcpXOVWP8Bi1ywY62kCiOTsH/x7wQrGnj34Pt5FoLcCAyvY5GLcg70AmmZ3iJDZ7iP4WFLDc+JKvYKkMOPRbisiSCpISY/E/Q4S5fd0O75YrlTAlKiNuHdrJ6CFWSyVxluwakLuHPkqwDi7j6O9HBEehRrt/0tPXI/1GbNgom2kRcj9xD+A/hAN+gDCmt7M8Lt95MAkt5DjgKTE0oQCLXcTI6kGk6WnIv00U+YA/Jop5QQbKjI4wNOhUASd/elqSBFR/5Hay3VCVMMpcSBRQHTsE9bMH0js0U8Qr0ky54ZYANPtlLu5RYamIXbx9n9VjdquT5g3UOeQ4AYh7DkhBQTUStNGme9FocQrCAIRQ04gQKrM73J8+wN1BpqJnGB3/Le2pkQY7LE4YHOy45luUE/ofqgw3cg=
android:
  components:
  - tools
  - tools
  - platform-tools
  - android-${ANDROID_API_LEVEL}
  - build-tools-${ANDROID_BUILD_TOOLS_VERSION}
  - extra
script:
- "./gradlew buildRelease"


before_deploy:
- openssl aes-256-cbc -K $encrypted_9b3174215596_key -iv $encrypted_9b3174215596_iv -in release.keystore.jks.enc -out release.keystore.jks -d
- cd app/build/outputs/apk/release
- jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore ${TRAVIS_BUILD_DIR}/release.keystore.jks -storepass $storepass -keypass $keypass app-release-unsigned.apk kmptestkeyAl
- jarsigner -verify app-release-unsigned.apk
- "${ANDROID_HOME}/build-tools/${ANDROID_BUILD_TOOLS}/zipalign -v 4 app-release-unsigned.apk TravisAndroid.apk"
- cd -
- scripts/tag.sh

deploy:
  provider: releases
  on:
    branch: master
  api_key:
    secure: "YXzDh3KNolH0KuGJ4CTdwFidso7uI16ZpEEYaSYIPJp0+jvCXd2/1BL/ouyvUURsly4g8n3CCnRHmtGKO0x9VboX5iHUeCA8zziPUs8WdLJGx63TuwB1yGsYozX4f7ojlfbYzl1B6eK+U5RtEzFO6ro39AGKvKSoaVV1uMLJL0/Qk5zuDNHs3CTkBPTkj+BwrhTJzrDU/RtB/sWof5dAR0xAgZUx6xCkOIoWZK/SQ5sJNe18s62yMxk9rXNH5Bz8sAI4vs8CWTK6cWvcCLhHAPogmraiJ8bMjg5OrG5dV/FH9MafIsJLGLpna4Hn43MQC2qec70krNlVtdOvmhvi5lKuFiNT2TPa2o/3IlqfWYzlLAWckVdnjSQapXbVqyNdtTMJKO6gUTBy7XW9h+DhMMHm0So0jp5L58qJVzHPSWLxvUmYc99jErfz77fif7iBTcxt0mJlyMhqqLro0vIubFH/pmxe2bzKQuXmn1JO3l1e7hk9PqPd2gBc1SifCzwit15X09TjKUJsclLqrHjv6Tt6tgcAI1JPCpV0+/+VqJDwMKanEDWQEoOCFTEVB/RvtxbZ9LDOscLQrx35lx55kPeel2LiEESMkzzvhc6g6+8LkZ6whPwBDJCyHGrZ1eBz7whJcBwI3VKO6RoPt/w71JNrmYJmKHYSZri09xql7IM="
  file: "app/build/outputs/apk/release/TravisAndroid.apk"
  overwrite: true
  skip_cleanup: true
  